<?php
/*======================================================================*\
|| #################################################################### ||
|| # Package - Joomla Template based on YJSimpleGrid Framework          ||
|| # Copyright (C) 2010  Youjoomla LLC. All Rights Reserved.            ||
|| # license - PHP files are licensed under  GNU/GPL V2                 ||
|| # license - CSS  - JS - IMAGE files  are Copyrighted material        ||
|| # bound by Proprietary License of Youjoomla.com                      ||
|| # for more information visit http://www.youjoomla.com/license.html   ||
|| # Redistribution and  modification of this software                  ||
|| # is bounded by its licenses                                         ||
|| # websites - http://www.youjoomla.com | http://www.yjsimplegrid.com  ||
|| #################################################################### ||
\*======================================================================*/
defined( '_JEXEC' ) or die( 'Restricted index access' );
/*  
  !!! DO NOT EDIT THIS FILE. IT MIGHT BE CHANGED ON UPDATE
  this file is custom for this template only. if you wish to edit or add 
  own code to the template, use template_name/custom/yjsg_custom_params.php
  
*/
/*

	this variable is for custom link color. you can use it to style any HTML elements
	see instructions here:
	http://www.yjsimplegrid.com/documentation/advanced/elements-styling-based-on-link-color.html

*/
	
$cc_css ="a{color:".$style_color.";}";
$cc_css .="[class*='yjsg-button-color']{background:".$style_color.";}[class*='yjsg-button-color']:hover{background:".$yjsg_color->darker('5%').";}";
$cc_css .="#typosticky.yjsg-sticky.fixed{max-width:".$css_width.$css_widthdefined.";margin:0 auto;padding:15px;}";
$cc_css .=".yjsg-sub-heading,.yjsg-sticky-menu a.active-scroll,[data-sticky-block] a.active-scroll:before{border-color:".$style_color.";}";
$cc_css .="[class*='facolor'].fa:before{color:".$style_color.";}";

// custom bootstrap buttons backgrounds per style. Bypassing the template link color and going with template hover instead 
switch ($css_file) {
    case 'blue':
        $valid_color = '4093DC';
        break;
    case 'green':
        $valid_color = '91965a';
        break;
    case 'orange':
        $valid_color = 'ff6600';
        break;
     case 'red':
        $valid_color = 'c92c2c';
        break;
        default:
       $valid_color = '4093DC';
}
//-- TOP MENU VERTICAL OFFSET --
//top menu top offsets | if empty top offset is 30 otherwise top offset is what you set here --
$DDverticalTopOffset =46;// SmoothDropdown
$DLverticalTopOffset =26;// SmoothDropline

/* K2 CSS */
if (JFactory::getApplication()->input->get( 'option' ) == 'com_k2' 
	|| JModuleHelper::getModule( 'k2_content' )
	|| JModuleHelper::getModule( 'k2_tools' )
	|| JModuleHelper::getModule( 'k2_comments' )
	){
		$document->addStyleSheet($yj_site.'css/customk.css');
}
/*JS IMAGE EFFECT */
$YjsgCustomJS	= array();
$YjsgCustomJS[] = $yj_site.'src/styles.js';

$yjsg6_before ='<div class="yjsg6_out">';
$yjsg6_after  ='<div class="yjsg6_bottom"></div></div>';

$yjsg7_before ='<div class="yjsg7_out">';
$yjsg7_after  ='</div>';

// conditional css
if ( $default_menu_style == 3 || $default_menu_style == 4 ){
	
	$document->addStyleDeclaration("ul.subul_main.dropline.level1 li a{padding:7px 20px 7px 0!important;}ul.subul_main.dropline.level2 li a,	  ul.subul_main.dropline.level3 li a,ul.subul_main.dropline.level4 li a{padding:7px 0!important;}ul.subul_main.dropline.level1 li.haschild span.child a, ul.subul_main.dropline.level1 li.haschild span.child a:hover {background-position:90% center!important;}");
	
}

if ($default_menu_style == 4 ){
	$document->addStyleDeclaration(".top_menu ul.subul_main.dropline.level2{margin-top:17px!important;}");
}

if($yjsgBrowser->Name == 'msie' || strpos($_SERVER['HTTP_USER_AGENT'], 'Trident/7.0; rv:11.0') !== false){
	 $document->addStyleDeclaration(".hdcis .navContainer_inside:after{margin:0 0 0 -3px!important;}");
}

if($yjsgBrowser->Name == 'chrome' || $yjsgBrowser->Name == 'safari'){
	 $document->addStyleDeclaration(".hdck2tc div.k2TagCloudBlock a:after{margin:-25px 0px 0 28px!important;}");
}

if($yjsgBrowser->Name == 'opera'){
	 $document->addStyleDeclaration("#header{overflow:visible;}.hdcis .navContainer_inside:after{margin:-32px 0 0 97px;}");
}

if($yjsgBrowser->Name == 'msie' && $yjsgBrowser->Version == '8.0'){
	 $document->addStyleDeclaration(".yy_slideitems_in{height:auto!important;}");
}

if ($this->countModules('left') || $this->countModules('right') || $this->countModules('inset') ) { 
		if( $site_layout == 1){
		 $document->addStyleDeclaration("
				 #midblock{
					box-shadow:inset 0px 1px 0px 0px #dbdbdb,inset 0px 2px 0px 0px #fff;
					-webkit-box-shadow:inset 0px 1px 0px 0px #dbdbdb,inset 0px 2px 0px 0px #fff;
					background: rgb(249,249,249)!important;
					background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMTAwJSIgeDI9IjEwMCUiIHkyPSIwJSI+CiAgICA8c3RvcCBvZmZzZXQ9Ijc0JSIgc3RvcC1jb2xvcj0iI2Y5ZjlmOSIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiNlZWVlZWUiIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
					background: -moz-linear-gradient(45deg,  rgba(249,249,249,1) 74%, rgba(238,238,238,1) 100%)!important; 
					background: -webkit-gradient(linear, left bottom, right top, color-stop(74%,rgba(249,249,249,1)), color-stop(100%,rgba(238,238,238,1)));
					background: -webkit-linear-gradient(45deg,  rgba(249,249,249,1) 74%,rgba(238,238,238,1) 100%)!important;
					background: -o-linear-gradient(45deg,  rgba(249,249,249,1) 74%,rgba(238,238,238,1) 100%)!important;
					background: -ms-linear-gradient(45deg,  rgba(249,249,249,1) 74%,rgba(238,238,238,1) 100%)!important;
					background: linear-gradient(45deg,  rgba(249,249,249,1) 74%,rgba(238,238,238,1) 100%)!important;
					filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f9f9f9', endColorstr='#eeeeee',GradientType=1 ); 
				}
		 ");
		}else if( $site_layout == 2){
		 $document->addStyleDeclaration("
				 #midblock{
					box-shadow:inset 0px 1px 0px 0px #dbdbdb,inset 0px 2px 0px 0px #fff;
					-webkit-box-shadow:inset 0px 1px 0px 0px #dbdbdb,inset 0px 2px 0px 0px #fff;
					background: rgb(249,249,249)!important;
					background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMTAwJSIgeDI9IjEwMCUiIHkyPSIwJSI+CiAgICA8c3RvcCBvZmZzZXQ9Ijc0JSIgc3RvcC1jb2xvcj0iI2Y5ZjlmOSIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiNlZWVlZWUiIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
					background: -moz-linear-gradient(45deg,  rgba(249,249,249,1) 74%, rgba(238,238,238,1) 100%)!important; 
					background: -webkit-gradient(linear, left bottom, right top, color-stop(74%,rgba(249,249,249,1)), color-stop(100%,rgba(238,238,238,1)));
					background: -webkit-linear-gradient(45deg,  rgba(249,249,249,1) 74%,rgba(238,238,238,1) 100%)!important;
					background: -o-linear-gradient(45deg,  rgba(249,249,249,1) 74%,rgba(238,238,238,1) 100%)!important;
					background: -ms-linear-gradient(45deg,  rgba(249,249,249,1) 74%,rgba(238,238,238,1) 100%)!important;
					background: linear-gradient(45deg,  rgba(249,249,249,1) 74%,rgba(238,238,238,1) 100%)!important;
					filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f9f9f9', endColorstr='#eeeeee',GradientType=1 ); 
				}
		 ");
		}else if($site_layout == 3){
			$document->addStyleDeclaration("
				#midblock,.hdcmt ul#tabs, .hdcmt #yy_container_intheaters, .hdcmt #yy_container_comingsoon, 
				.hdcmt #yy_container_bestof2012{
					box-shadow:inset 0px 1px 0px 0px #dbdbdb,inset 0px 2px 0px 0px #fff;
					-webkit-box-shadow:inset 0px 1px 0px 0px #dbdbdb,inset 0px 2px 0px 0px #fff;
					background: rgb(238,238,238)!important;
					background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIxMDAlIiB5Mj0iMTAwJSI+CiAgICA8c3RvcCBvZmZzZXQ9IjAlIiBzdG9wLWNvbG9yPSIjZWVlZWVlIiBzdG9wLW9wYWNpdHk9IjEiLz4KICAgIDxzdG9wIG9mZnNldD0iMjUlIiBzdG9wLWNvbG9yPSIjZjlmOWY5IiBzdG9wLW9wYWNpdHk9IjEiLz4KICA8L2xpbmVhckdyYWRpZW50PgogIDxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSIxIiBoZWlnaHQ9IjEiIGZpbGw9InVybCgjZ3JhZC11Y2dnLWdlbmVyYXRlZCkiIC8+Cjwvc3ZnPg==);
					background: -moz-linear-gradient(-45deg,  rgba(238,238,238,1) 0%, rgba(249,249,249,1) 25%)!important;
					background: -webkit-gradient(linear, left top, right bottom, color-stop(0%,rgba(238,238,238,1)), color-stop(25%,rgba(249,249,249,1)))!important;
					background: -webkit-linear-gradient(-45deg,  rgba(238,238,238,1) 0%,rgba(249,249,249,1) 25%)!important; 
					background: -o-linear-gradient(-45deg,  rgba(238,238,238,1) 0%,rgba(249,249,249,1) 25%)!important; 
					background: -ms-linear-gradient(-45deg,  rgba(238,238,238,1) 0%,rgba(249,249,249,1) 25%)!important;
					background: linear-gradient(135deg,  rgba(238,238,238,1) 0%,rgba(249,249,249,1) 25%)!important;
					filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#eeeeee', endColorstr='#f9f9f9',GradientType=1 )!important; 
			  }		
			");			
		}
}
if ($text_direction == 1 && ($this->countModules('left') || $text_direction == 1 && $this->countModules('right') || $text_direction == 1 && $this->countModules('inset')) ) {
	
	$document->addStyleDeclaration("
        #midblock{
            box-shadow:inset 0px 1px 0px 0px #dbdbdb,inset 0px 2px 0px 0px #fff;
            -webkit-box-shadow:inset 0px 1px 0px 0px #dbdbdb,inset 0px 2px 0px 0px #fff;
			background: rgb(238,238,238)!important;
			background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIxMDAlIiB5Mj0iMTAwJSI+CiAgICA8c3RvcCBvZmZzZXQ9IjAlIiBzdG9wLWNvbG9yPSIjZWVlZWVlIiBzdG9wLW9wYWNpdHk9IjEiLz4KICAgIDxzdG9wIG9mZnNldD0iMjUlIiBzdG9wLWNvbG9yPSIjZjlmOWY5IiBzdG9wLW9wYWNpdHk9IjEiLz4KICA8L2xpbmVhckdyYWRpZW50PgogIDxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSIxIiBoZWlnaHQ9IjEiIGZpbGw9InVybCgjZ3JhZC11Y2dnLWdlbmVyYXRlZCkiIC8+Cjwvc3ZnPg==);
			background: -moz-linear-gradient(-45deg,  rgba(238,238,238,1) 0%, rgba(249,249,249,1) 25%)!important;
			background: -webkit-gradient(linear, left top, right bottom, color-stop(0%,rgba(238,238,238,1)), color-stop(25%,rgba(249,249,249,1)))!important;
			background: -webkit-linear-gradient(-45deg,  rgba(238,238,238,1) 0%,rgba(249,249,249,1) 25%)!important; 
			background: -o-linear-gradient(-45deg,  rgba(238,238,238,1) 0%,rgba(249,249,249,1) 25%)!important; 
			background: -ms-linear-gradient(-45deg,  rgba(238,238,238,1) 0%,rgba(249,249,249,1) 25%)!important;
			background: linear-gradient(135deg,  rgba(238,238,238,1) 0%,rgba(249,249,249,1) 25%)!important;
			filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#eeeeee', endColorstr='#f9f9f9',GradientType=1 )!important; 
	  }		
	");
}
?>